version: '2'

services:
  redis:
    image: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  app:
    build:
      dockerfile: app/Dockerfile
    volumes:
      - /home/timur/IPR/telegram_bot:/data